# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

# Set up the OS and Python version
build:
  os: ubuntu-24.04
  tools:
    python: "3.12"  # Use a stable Python version

# Specify Sphinx build directory
sphinx:
  configuration: docs/source/conf.py

# Use Poetry to install dependencies
python:
  install:
    - method: poetry
