site_name: Djangautomate
repo_url: https://github.com/0rac130fD31phi/djangautomate
theme:
  name: material

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - API Reference: api_reference.md
  - Contributing: contributing.md
